# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/litestruct',
                'doc_host': 'https://gautam-e.github.io',
                'git_url': 'https://github.com/gautam-e/litestruct',
                'lib_path': 'litestruct'},
  'syms': {'litestruct.core': {'litestruct.core.structured_output': ('core.html#structured_output', 'litestruct/core.py')}}}
